repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0 # Usa l'ultima versione
    hooks:
      - id: ruff
        args: [ --fix ] # Corregge automaticamente gli errori semplici
      - id: ruff-format # Sostituisce Black (formatta il codice)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        additional_dependencies: [pydantic, fastapi] # Importante per la tua API